-- MASRAHI — صلاحيات المدير/الأستاذ مع Supabase Auth + RLS
-- نفّذ هذا الملف داخل Supabase SQL Editor بعد إنشاء المشروع.

create type public.app_role as enum ('admin', 'director');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role public.app_role not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  level text not null,
  day_of_week smallint not null,
  start_time time not null,
  duration integer not null,
  sort_order integer not null default 0,
  is_public boolean not null default true
);

create table if not exists public.scripts (
  id bigint generated by default as identity primary key,
  title text not null,
  level text not null,
  duration text not null default '',
  character_count integer not null default 0,
  characters text not null default '',
  full_text text not null default '',
  scenes text not null default '',
  direction_notes text not null default '',
  staging_notes text not null default '',
  sound_effects text not null default '',
  music text not null default '',
  lighting text not null default '',
  scenography text not null default '',
  accessories text not null default '',
  techniques text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  date date not null,
  start_time time not null,
  duration integer not null,
  topic text not null default '',
  objectives text not null default '',
  activities text not null default '',
  techniques text[] not null default '{}',
  teacher_notes text not null default '',
  difficulties text not null default '',
  students_needing_support text not null default '',
  next_session_plan text not null default '',
  script_id bigint references public.scripts(id) on delete set null,
  scene_info text not null default '',
  status text not null default 'scheduled' check (status in ('scheduled', 'completed', 'postponed', 'cancelled')),
  session_number integer not null default 1,
  is_holiday boolean not null default false,
  holiday_name text
);

create index if not exists sessions_class_date_idx on public.sessions(class_id, date);

create or replace function public.current_user_role()
returns public.app_role
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where id = auth.uid()
  limit 1
$$;

alter table public.profiles enable row level security;
alter table public.classes enable row level security;
alter table public.scripts enable row level security;
alter table public.sessions enable row level security;

revoke all on table public.profiles from anon, authenticated;
revoke all on table public.classes from anon, authenticated;
revoke all on table public.scripts from anon, authenticated;
revoke all on table public.sessions from anon, authenticated;

grant select on table public.classes to anon, authenticated;
grant select on table public.profiles, public.scripts, public.sessions to authenticated;
grant insert, update, delete on table public.classes, public.scripts, public.sessions to authenticated;

drop policy if exists "profiles_self_or_admin_select" on public.profiles;
create policy "profiles_self_or_admin_select"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists "profiles_admin_update" on public.profiles;
create policy "profiles_admin_update"
on public.profiles
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "classes_public_or_staff_select" on public.classes;
create policy "classes_public_or_staff_select"
on public.classes
for select
to anon, authenticated
using (is_public = true or public.current_user_role() in ('admin', 'director'));

drop policy if exists "classes_admin_insert" on public.classes;
create policy "classes_admin_insert"
on public.classes
for insert
to authenticated
with check (public.current_user_role() = 'admin');

drop policy if exists "classes_admin_update" on public.classes;
create policy "classes_admin_update"
on public.classes
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "classes_admin_delete" on public.classes;
create policy "classes_admin_delete"
on public.classes
for delete
to authenticated
using (public.current_user_role() = 'admin');

drop policy if exists "scripts_staff_select" on public.scripts;
create policy "scripts_staff_select"
on public.scripts
for select
to authenticated
using (public.current_user_role() in ('admin', 'director'));

drop policy if exists "scripts_admin_insert" on public.scripts;
create policy "scripts_admin_insert"
on public.scripts
for insert
to authenticated
with check (public.current_user_role() = 'admin');

drop policy if exists "scripts_admin_update" on public.scripts;
create policy "scripts_admin_update"
on public.scripts
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "scripts_admin_delete" on public.scripts;
create policy "scripts_admin_delete"
on public.scripts
for delete
to authenticated
using (public.current_user_role() = 'admin');

drop policy if exists "sessions_staff_select" on public.sessions;
create policy "sessions_staff_select"
on public.sessions
for select
to authenticated
using (public.current_user_role() in ('admin', 'director'));

drop policy if exists "sessions_admin_insert" on public.sessions;
create policy "sessions_admin_insert"
on public.sessions
for insert
to authenticated
with check (public.current_user_role() = 'admin');

drop policy if exists "sessions_admin_update" on public.sessions;
create policy "sessions_admin_update"
on public.sessions
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "sessions_admin_delete" on public.sessions;
create policy "sessions_admin_delete"
on public.sessions
for delete
to authenticated
using (public.current_user_role() = 'admin');

grant usage, select on all sequences in schema public to authenticated;
