-- MASRAHI — صلاحيات المدير/الأستاذ مع Supabase Auth + RLS
-- نفّذ هذا الملف داخل Supabase SQL Editor بعد إنشاء المشروع.

create type public.app_role as enum ('admin', 'director');

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  role public.app_role not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.classes (
  id bigint generated by default as identity primary key,
  name text not null,
  level text not null,
  day_of_week smallint not null,
  start_time time not null,
  duration integer not null,
  sort_order integer not null default 0,
  is_public boolean not null default true
);

create table if not exists public.scripts (
  id bigint generated by default as identity primary key,
  title text not null,
  level text not null,
  duration text not null default '',
  character_count integer not null default 0,
  characters text not null default '',
  full_text text not null default '',
  scenes text not null default '',
  direction_notes text not null default '',
  staging_notes text not null default '',
  sound_effects text not null default '',
  music text not null default '',
  lighting text not null default '',
  scenography text not null default '',
  accessories text not null default '',
  techniques text[] not null default '{}',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.holidays (
  id bigint generated by default as identity primary key,
  name text not null,
  start_date date not null,
  end_date date not null,
  type text not null default 'vacation'
);

create table if not exists public.programs (
  id bigint generated by default as identity primary key,
  academic_year text not null unique,
  title text not null default 'البرنامج السنوي'
);

create table if not exists public.program_phases (
  id text primary key,
  program_id bigint references public.programs(id) on delete cascade,
  title text not null,
  description text not null default '',
  objectives jsonb not null default '[]'::jsonb,
  activities jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0
);

create table if not exists public.lesson_sheets (
  id bigint generated by default as identity primary key,
  class_id bigint references public.classes(id) on delete cascade,
  program_phase_id text references public.program_phases(id) on delete set null,
  session_number integer,
  date date,
  title text not null,
  objectives text not null default '',
  drills jsonb not null default '[]'::jsonb,
  teacher_instructions text not null default '',
  observations text not null default '',
  assessment text not null default ''
);

create table if not exists public.settings (
  id bigint generated by default as identity primary key,
  teacher_name text not null default '',
  school_name text not null default '',
  academic_year text not null default '2026/2027'
);

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  class_id bigint not null references public.classes(id) on delete cascade,
  date date not null,
  start_time time not null,
  duration integer not null,
  topic text not null default '',
  objectives text not null default '',
  activities text not null default '',
  techniques text[] not null default '{}',
  teacher_notes text not null default '',
  difficulties text not null default '',
  students_needing_support text not null default '',
  next_session_plan text not null default '',
  script_id bigint references public.scripts(id) on delete set null,
  scene_info text not null default '',
  status text not null default 'scheduled' check (status in ('scheduled', 'completed', 'postponed', 'cancelled')),
  session_number integer not null default 1,
  is_holiday boolean not null default false,
  holiday_name text
);

create index if not exists sessions_class_date_idx on public.sessions(class_id, date);

create table if not exists public.session_attendance (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.sessions(id) on delete cascade,
  student_name text not null,
  status text not null default 'present' check (status in ('present','absent','late','excused')),
  note text not null default ''
);

create table if not exists public.training_logs (
  id bigint generated by default as identity primary key,
  class_id bigint references public.classes(id) on delete cascade,
  session_id bigint references public.sessions(id) on delete set null,
  date date not null,
  notes text not null default ''
);

create or replace function public.current_user_role()
returns public.app_role
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where id = auth.uid()
  limit 1
$$;

alter table public.profiles enable row level security;
alter table public.holidays enable row level security;
alter table public.programs enable row level security;
alter table public.program_phases enable row level security;
alter table public.lesson_sheets enable row level security;
alter table public.settings enable row level security;
alter table public.session_attendance enable row level security;
alter table public.training_logs enable row level security;
alter table public.classes enable row level security;
alter table public.scripts enable row level security;
alter table public.sessions enable row level security;

revoke all on table public.profiles, public.holidays, public.programs, public.program_phases, public.lesson_sheets, public.settings, public.session_attendance, public.training_logs from anon, authenticated;
revoke all on table public.profiles from anon, authenticated;
revoke all on table public.classes from anon, authenticated;
revoke all on table public.scripts from anon, authenticated;
revoke all on table public.sessions from anon, authenticated;

grant select on table public.classes to anon, authenticated;
grant select on table public.holidays, public.programs, public.program_phases, public.lesson_sheets, public.settings to anon, authenticated;
grant select on table public.session_attendance, public.training_logs to authenticated;
grant insert, update, delete on table public.holidays, public.programs, public.program_phases, public.lesson_sheets, public.settings, public.session_attendance, public.training_logs to authenticated;
grant select on table public.profiles, public.scripts, public.sessions to authenticated;
grant insert, update, delete on table public.classes, public.scripts, public.sessions to authenticated;

drop policy if exists "profiles_self_or_admin_select" on public.profiles;
create policy "profiles_self_or_admin_select"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.current_user_role() = 'admin');

drop policy if exists "profiles_admin_update" on public.profiles;
create policy "profiles_admin_update"
on public.profiles
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "classes_public_or_staff_select" on public.classes;
create policy "classes_public_or_staff_select"
on public.classes
for select
to anon, authenticated
using (is_public = true or public.current_user_role() in ('admin', 'director'));

drop policy if exists "classes_admin_insert" on public.classes;
create policy "classes_admin_insert"
on public.classes
for insert
to authenticated
with check (public.current_user_role() = 'admin');

drop policy if exists "classes_admin_update" on public.classes;
create policy "classes_admin_update"
on public.classes
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "classes_admin_delete" on public.classes;
create policy "classes_admin_delete"
on public.classes
for delete
to authenticated
using (public.current_user_role() = 'admin');

drop policy if exists "scripts_staff_select" on public.scripts;
create policy "scripts_staff_select"
on public.scripts
for select
to authenticated
using (public.current_user_role() in ('admin', 'director'));

drop policy if exists "scripts_admin_insert" on public.scripts;
create policy "scripts_admin_insert"
on public.scripts
for insert
to authenticated
with check (public.current_user_role() = 'admin');

drop policy if exists "scripts_admin_update" on public.scripts;
create policy "scripts_admin_update"
on public.scripts
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "scripts_admin_delete" on public.scripts;
create policy "scripts_admin_delete"
on public.scripts
for delete
to authenticated
using (public.current_user_role() = 'admin');

drop policy if exists "sessions_staff_select" on public.sessions;
create policy "sessions_staff_select"
on public.sessions
for select
to authenticated
using (public.current_user_role() in ('admin', 'director'));

drop policy if exists "sessions_admin_insert" on public.sessions;
create policy "sessions_admin_insert"
on public.sessions
for insert
to authenticated
with check (public.current_user_role() = 'admin');

drop policy if exists "sessions_admin_update" on public.sessions;
create policy "sessions_admin_update"
on public.sessions
for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "sessions_admin_delete" on public.sessions;
create policy "sessions_admin_delete"
on public.sessions
for delete
to authenticated
using (public.current_user_role() = 'admin');

grant usage, select on all sequences in schema public to authenticated;


-- القراءة العامة للمحتوى المنشور.
drop policy if exists "holidays_public_select" on public.holidays;
create policy "holidays_public_select" on public.holidays for select to anon, authenticated using (true);

drop policy if exists "programs_public_select" on public.programs;
create policy "programs_public_select" on public.programs for select to anon, authenticated using (true);

drop policy if exists "program_phases_public_select" on public.program_phases;
create policy "program_phases_public_select" on public.program_phases for select to anon, authenticated using (true);

drop policy if exists "lesson_sheets_staff_select" on public.lesson_sheets;
create policy "lesson_sheets_staff_select" on public.lesson_sheets for select to authenticated using (public.current_user_role() in ('admin','director'));

drop policy if exists "settings_public_select" on public.settings;
create policy "settings_public_select" on public.settings for select to anon, authenticated using (true);

drop policy if exists "admin_holidays_write" on public.holidays;
create policy "admin_holidays_write" on public.holidays for all to authenticated using (public.current_user_role()='admin') with check (public.current_user_role()='admin');

drop policy if exists "admin_programs_write" on public.programs;
create policy "admin_programs_write" on public.programs for all to authenticated using (public.current_user_role()='admin') with check (public.current_user_role()='admin');

drop policy if exists "admin_program_phases_write" on public.program_phases;
create policy "admin_program_phases_write" on public.program_phases for all to authenticated using (public.current_user_role()='admin') with check (public.current_user_role()='admin');

drop policy if exists "admin_lesson_sheets_write" on public.lesson_sheets;
create policy "admin_lesson_sheets_write" on public.lesson_sheets for all to authenticated using (public.current_user_role()='admin') with check (public.current_user_role()='admin');

drop policy if exists "admin_settings_write" on public.settings;
create policy "admin_settings_write" on public.settings for all to authenticated using (public.current_user_role()='admin') with check (public.current_user_role()='admin');

drop policy if exists "staff_attendance_select" on public.session_attendance;
create policy "staff_attendance_select" on public.session_attendance for select to authenticated using (public.current_user_role() in ('admin','director'));

drop policy if exists "admin_attendance_write" on public.session_attendance;
create policy "admin_attendance_write" on public.session_attendance for all to authenticated using (public.current_user_role()='admin') with check (public.current_user_role()='admin');

drop policy if exists "staff_training_logs_select" on public.training_logs;
create policy "staff_training_logs_select" on public.training_logs for select to authenticated using (public.current_user_role() in ('admin','director'));

drop policy if exists "admin_training_logs_write" on public.training_logs;
create policy "admin_training_logs_write" on public.training_logs for all to authenticated using (public.current_user_role()='admin') with check (public.current_user_role()='admin');
